name: Check for new release and update Yagna versions.

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 3 * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: curl -sS https://join.golem.network/as-provider > install.sh
      - run: cat install.sh | sed -nE 's/^.*YA_INSTALLER_CORE="?\$\{YA_INSTALLER_CORE:-v([^}]+)\}"?.*$/YA_INSTALLER_CORE=\1/p' >> $GITHUB_ENV
      - run: cat install.sh | sed -nE 's/^.*YA_INSTALLER_WASI="?\$\{YA_INSTALLER_WASI:-v([^}]+)\}"?.*$/YA_INSTALLER_WASI=\1/p' >> $GITHUB_ENV
      - run: cat install.sh | sed -nE 's/^.*YA_INSTALLER_VM="?\$\{YA_INSTALLER_VM:-v([^}]+)\}"?.*$/YA_INSTALLER_VM=\1/p' >> $GITHUB_ENV
      - run: sed -i -E 's/(ARG YA_CORE_VERSION=)\S+/\1${{ env.YA_INSTALLER_CORE }}/' docker/Dockerfile
      - run: sed -i -E 's/(ARG YA_WASI_VERSION=)\S+/\1${{ env.YA_INSTALLER_WASI }}/' docker/Dockerfile
      - run: sed -i -E 's/(ARG YA_VM_VERSION=)\S+/\1${{ env.YA_INSTALLER_VM }}/' docker/Dockerfile
      - run: rm install.sh
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: "chore: upgrade Yagna to v${{ env.YA_INSTALLER_CORE }}"
          title: "chore: upgrade Yagna to v${{ env.YA_INSTALLER_CORE }}"
          branch: patch/yagna-${{ env.YA_INSTALLER_CORE }}
          reviewers:  ${{ github.repository_owner }}
          delete-branch: true
